 DROP TABLE PRODUCTS IF EXISTS;   
 CREATE TABLE PRODUCTS (  
 ID VARCHAR(25) PRIMARY KEY, 
 NAME VARCHAR(50),    
 DESCRIPTION  VARCHAR(250), 
 UNIT_PRICE DECIMAL,   
 MANUFACTURER VARCHAR(50), 
 CATEGORY VARCHAR(50),  
 CONDITN VARCHAR(50), 
 UNITS_IN_STOCK BIGINT,  
 UNITS_IN_ORDER BIGINT,   
 DISCONTINUED BOOLEAN   
 ); 
 
 DROP TABLE CUSTOMER IF exists;
 CREATE TABLE CUSTOMER( 
 ID INT PRIMARY KEY,
 NAME VARCHAR(50),
 ADRESS  VARCHAR(50),
 NOOFORDERS INT);
 
 
 
 DROP TABLE CART IF EXISTS
 CREATE TABLE CART (
ID VARCHAR(50) PRIMARY KEY
);


DROP TABLE CART_ITEM IF EXISTS;
CREATE TABLE CART_ITEM (
ID VARCHAR(75),
PRODUCT_ID VARCHAR(25),
CART_ID varchar(50),
QUANTITY BIGINT,
FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(ID),
FOREIGN KEY (CART_ID) REFERENCES CART(ID),
CONSTRAINT CART_ITEM_PK PRIMARY KEY (ID,CART_ID)
);
 